# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DB_insert_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(542, 656)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLabel {\n"
"    color:rgb(35,35,35);\n"
"    font: 10pt \"Georgia\";\n"
"    margin-left :10px\n"
"}\n"
"QPushButton{\n"
"    font: 10pt \"Georgia\";\n"
"}\n"
"\n"
"QSpinBox{\n"
"    color: rgb(105,105,105);\n"
"    font: 10pt;\n"
"}\n"
"\n"
"QSpinBox{\n"
"    background-color: rgb(105,105,105);\n"
"    border-radius: 2px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"    padding-left: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: rgb(75,75,75);\n"
"    font: 10pt;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"    padding-left: 10px;\n"
"    margin-left :10px;\n"
"    margin-right:10;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(105,105,105);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(35,35,35);\n"
"}\n"
"/* RADIO BUTTON */\n"
"QRadioButton{\n"
"    color: black;\n"
"}\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(105,105,105);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(250,250,250);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(41, 65, 131);;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom_b.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(41, 65, 131);    \n"
"    background-color: rgb(41, 65, 131);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/*SPIN BOX*/\n"
"QSpinBox {\n"
"position: relative;\n"
"  padding: 4px;\n"
"  width: 50px;\n"
"  height: 20px;\n"
"  text-align: center;\n"
"  font-size: 2rem;\n"
" border-radius: 5px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"}\n"
"QSpinBox::up-button{\n"
"margin-top: 1px;\n"
"margin-right: 2px;\n"
"margin-left: -5px;\n"
"height: 10px;\n"
"background-image: url(:/16x16/icons/16x16/cil-arrow-top_b.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QSpinBox::down-button{\n"
"margin-left: 2px;\n"
"margin-top: -3px;\n"
"background-image: url(:/16x16/icons/16x16/cil-arrow-bottom_b.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QSpinBox::up-button:pressed{\n"
"    background-color: rgb(105,105,105);\n"
"}\n"
"QSpinBox::down-button:pressed{\n"
"    background-color: rgb(105,105,105);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_div_content_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_div_content_1.setGeometry(QtCore.QRect(0, 40, 541, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_div_content_1.sizePolicy().hasHeightForWidth())
        self.frame_div_content_1.setSizePolicy(sizePolicy)
        self.frame_div_content_1.setMinimumSize(QtCore.QSize(0, 110))
        self.frame_div_content_1.setMaximumSize(QtCore.QSize(16777215, 600))
        self.frame_div_content_1.setStyleSheet("background-color: rgb(250,250,250);\n"
"")
        self.frame_div_content_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_div_content_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_div_content_1.setObjectName("frame_div_content_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_div_content_1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_11.setMinimumSize(QtCore.QSize(19, 60))
        self.label_11.setStyleSheet("font: 12pt \"Arkhip\";\n"
"\n"
"margin-left :2px\n"
"")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.btn_info = QtWidgets.QPushButton(self.frame_div_content_1)
        self.btn_info.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid rgba(0,75,78,255);\n"
"    border-radius: 5px;    \n"
"    background-color: rgba(0,75,78,255);\n"
"    margin-left :10px;\n"
"    margin-right :10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(4,106,102);\n"
"    border: 2px solid rgb(4,76,82);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"")
        self.btn_info.setObjectName("btn_info")
        self.verticalLayout_7.addWidget(self.btn_info)
        self.label_10 = QtWidgets.QLabel(self.frame_div_content_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.label = QtWidgets.QLabel(self.frame_div_content_1)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.account = QtWidgets.QLineEdit(self.frame_div_content_1)
        self.account.setObjectName("account")
        self.verticalLayout_7.addWidget(self.account)
        self.label_3 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.bin_path = QtWidgets.QLineEdit(self.frame_div_content_1)
        self.bin_path.setObjectName("bin_path")
        self.verticalLayout_7.addWidget(self.bin_path)
        self.label_2 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.ppartition = QtWidgets.QLineEdit(self.frame_div_content_1)
        self.ppartition.setObjectName("ppartition")
        self.verticalLayout_7.addWidget(self.ppartition)
        self.label_4 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.spartition = QtWidgets.QLineEdit(self.frame_div_content_1)
        self.spartition.setObjectName("spartition")
        self.verticalLayout_7.addWidget(self.spartition)
        self.label_5 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.db_path = QtWidgets.QLineEdit(self.frame_div_content_1)
        self.db_path.setObjectName("db_path")
        self.verticalLayout_7.addWidget(self.db_path)
        self.label_8 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.anaconda = QtWidgets.QLineEdit(self.frame_div_content_1)
        self.anaconda.setObjectName("anaconda")
        self.verticalLayout_7.addWidget(self.anaconda)
        self.label_9 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.outfmt = QtWidgets.QLineEdit(self.frame_div_content_1)
        self.outfmt.setObjectName("outfmt")
        self.verticalLayout_7.addWidget(self.outfmt)
        self.label_7 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.insert = QtWidgets.QPushButton(self.frame_div_content_1)
        self.insert.setMinimumSize(QtCore.QSize(0, 30))
        self.insert.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid rgba(0,45,48,255);\n"
"    border-radius: 5px;    \n"
"    background-color: rgba(0,45,48,255);\n"
"    margin-left :10px;\n"
"    margin-right :10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(4,76,82);\n"
"    border: 2px solid rgb(4,76,82);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.insert.setObjectName("insert")
        self.verticalLayout_7.addWidget(self.insert)
        self.label_6 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.frame_top_btns = QtWidgets.QFrame(self.centralwidget)
        self.frame_top_btns.setGeometry(QtCore.QRect(0, 0, 541, 41))
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_top_btns.setStyleSheet("background-color: rgba(0,45,48,255)")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_top_btns.sizePolicy().hasHeightForWidth())
        self.frame_label_top_btns.setSizePolicy(sizePolicy)
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-terminal.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_10.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        font = QtGui.QFont()
        font.setFamily("Arkhip")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: 18pt \"Arkhip\";\n"
"")
        self.label_title_bar_top.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right.sizePolicy().hasHeightForWidth())
        self.frame_btns_right.setSizePolicy(sizePolicy)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right, 0, QtCore.Qt.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "User settings"))
        self.btn_info.setText(_translate("MainWindow", "Informations"))
        self.label.setText(_translate("MainWindow", "Account (es: accountname)"))
        self.label_3.setText(_translate("MainWindow", "Binary path (es: ./path/to/the/binary)"))
        self.label_2.setText(_translate("MainWindow", "Parallel partition (es: g100_user_prod)"))
        self.label_4.setText(_translate("MainWindow", "Serial partition (es: g100_all_serial)"))
        self.label_5.setText(_translate("MainWindow", "Database path (es: ./path/to/the/database)"))
        self.label_8.setText(_translate("MainWindow", "Anaconda Slurm module name (es: anaconda3)"))
        self.label_9.setText(_translate("MainWindow", "Out-format (es: \"6 qseqid sseqid slen sseq\") "))
        self.insert.setText(_translate("MainWindow", "Insert"))
        self.label_title_bar_top.setText(_translate("MainWindow", "Configuration panel"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
