# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1229, 964)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QLabel {\n"
"    color:rgb(35,35,35);\n"
"    font: 10pt \"Georgia\";\n"
"}\n"
"QPushButton{\n"
"    font: 10pt \"Georgia\";\n"
"}\n"
"\n"
"QSpinBox{\n"
"    color: rgb(105,105,105);\n"
"    font: 10pt;\n"
"}\n"
"\n"
"QSpinBox{\n"
"    background-color: rgb(105,105,105);\n"
"    border-radius: 2px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"    padding-left: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: rgb(75,75,75);\n"
"    font: 10pt;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(105,105,105);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(35,35,35);\n"
"}\n"
"/* RADIO BUTTON */\n"
"QRadioButton{\n"
"    color: black;\n"
"}\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(105,105,105);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(250,250,250);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(250,250,250);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/icons/16x16/cil-arrow-bottom_b.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(41, 65, 131);    \n"
"    background-color: rgb(41, 65, 131);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/*SPIN BOX*/\n"
"QSpinBox {\n"
"position: relative;\n"
"  padding: 4px;\n"
"  width: 50px;\n"
"  height: 20px;\n"
"  text-align: center;\n"
"  font-size: 2rem;\n"
" border-radius: 5px;\n"
"    border: 2px solid rgb(105,105,105);\n"
"}\n"
"QSpinBox::up-button{\n"
"margin-top: 1px;\n"
"margin-right: 2px;\n"
"margin-left: -5px;\n"
"height: 10px;\n"
"background-image: url(:/16x16/icons/16x16/cil-arrow-top_b.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QSpinBox::down-button{\n"
"margin-left: 2px;\n"
"margin-top: -3px;\n"
"background-image: url(:/16x16/icons/16x16/cil-arrow-bottom_b.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"QSpinBox::up-button:pressed{\n"
"    background-color: rgb(105,105,105);\n"
"}\n"
"QSpinBox::down-button:pressed{\n"
"    background-color: rgb(105,105,105);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_top_btns = QtWidgets.QFrame(self.centralwidget)
        self.frame_top_btns.setGeometry(QtCore.QRect(0, 20, 1231, 41))
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_top_btns.setStyleSheet("background-color: rgba(0,45,48,255)")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_top_btns.sizePolicy().hasHeightForWidth())
        self.frame_label_top_btns.setSizePolicy(sizePolicy)
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-terminal.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_10.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        font = QtGui.QFont()
        font.setFamily("Arkhip")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: 18pt \"Arkhip\";\n"
"")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right.sizePolicy().hasHeightForWidth())
        self.frame_btns_right.setSizePolicy(sizePolicy)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right, 0, QtCore.Qt.AlignRight)
        self.frame_div_content_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_div_content_1.setGeometry(QtCore.QRect(0, 150, 1231, 281))
        self.frame_div_content_1.setMinimumSize(QtCore.QSize(0, 110))
        self.frame_div_content_1.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_div_content_1.setStyleSheet("background-color: rgb(250,250,250);\n"
"")
        self.frame_div_content_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_div_content_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_div_content_1.setObjectName("frame_div_content_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_div_content_1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_11.setStyleSheet("font: 12pt \"Arkhip\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 3, 1, 1)
        self.wall_time = QtWidgets.QSpinBox(self.frame_div_content_1)
        self.wall_time.setMinimum(1)
        self.wall_time.setMaximum(24)
        self.wall_time.setObjectName("wall_time")
        self.gridLayout.addWidget(self.wall_time, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_div_content_1)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.account = QtWidgets.QComboBox(self.frame_div_content_1)
        self.account.setObjectName("account")
        self.gridLayout.addWidget(self.account, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_9.setMinimumSize(QtCore.QSize(5, 0))
        self.label_9.setMaximumSize(QtCore.QSize(10, 20))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.memory_per_node = QtWidgets.QSpinBox(self.frame_div_content_1)
        self.memory_per_node.setMinimum(1)
        self.memory_per_node.setObjectName("memory_per_node")
        self.gridLayout.addWidget(self.memory_per_node, 4, 3, 1, 1)
        self.number_of_processes = QtWidgets.QSpinBox(self.frame_div_content_1)
        self.number_of_processes.setMinimum(1)
        self.number_of_processes.setMaximum(500)
        self.number_of_processes.setObjectName("number_of_processes")
        self.gridLayout.addWidget(self.number_of_processes, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_7.setMaximumSize(QtCore.QSize(5, 20))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.partition = QtWidgets.QComboBox(self.frame_div_content_1)
        self.partition.setObjectName("partition")
        self.gridLayout.addWidget(self.partition, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_div_content_1)
        self.label_21.setMaximumSize(QtCore.QSize(5, 20))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 1, 4, 1, 1)
        self.threads = QtWidgets.QSpinBox(self.frame_div_content_1)
        self.threads.setMinimum(1)
        self.threads.setMaximum(500)
        self.threads.setObjectName("threads")
        self.gridLayout.addWidget(self.threads, 6, 3, 1, 1)
        self.serial_partition = QtWidgets.QLabel(self.frame_div_content_1)
        self.serial_partition.setStyleSheet("color: rgb(120, 120, 120);")
        self.serial_partition.setObjectName("serial_partition")
        self.gridLayout.addWidget(self.serial_partition, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.image_settings = QtWidgets.QLabel(self.centralwidget)
        self.image_settings.setGeometry(QtCore.QRect(0, 60, 1231, 91))
        self.image_settings.setStyleSheet("background-image: url(:/root/icons/settings.jpg);")
        self.image_settings.setText("")
        self.image_settings.setObjectName("image_settings")
        self.image_software = QtWidgets.QLabel(self.centralwidget)
        self.image_software.setGeometry(QtCore.QRect(0, 430, 1231, 91))
        self.image_software.setStyleSheet("background-image: url(:/root/icons/dna.png);")
        self.image_software.setText("")
        self.image_software.setObjectName("image_software")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 520, 1231, 421))
        self.verticalFrame.setStyleSheet("background-color: rgb(250,250,250);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.frame_div_content_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.frame_div_content_2.setObjectName("frame_div_content_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tools = QtWidgets.QComboBox(self.verticalFrame)
        self.tools.setObjectName("tools")
        self.gridLayout_2.addWidget(self.tools, 7, 1, 1, 1)
        self.bin_path = QtWidgets.QComboBox(self.verticalFrame)
        self.bin_path.setObjectName("bin_path")
        self.gridLayout_2.addWidget(self.bin_path, 4, 2, 1, 1)
        self.input_path = QtWidgets.QLineEdit(self.verticalFrame)
        self.input_path.setInputMask("")
        self.input_path.setObjectName("input_path")
        self.gridLayout_2.addWidget(self.input_path, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.verticalFrame)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 5, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.verticalFrame)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalFrame)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.verticalFrame)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.diamond = QtWidgets.QRadioButton(self.verticalFrame)
        self.diamond.setObjectName("diamond")
        self.horizontalLayout.addWidget(self.diamond)
        self.blast = QtWidgets.QRadioButton(self.verticalFrame)
        self.blast.setObjectName("blast")
        self.horizontalLayout.addWidget(self.blast)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.pa_env = QtWidgets.QCheckBox(self.verticalFrame)
        self.pa_env.setMinimumSize(QtCore.QSize(0, 40))
        self.pa_env.setStyleSheet("\n"
"  QCheckBox {\n"
"    background-color: #fff;\n"
"    height: 28px;\n"
"    width: 28px;\n"
"  }\n"
"\n"
"  QCheckBox:after {\n"
"    border: 2px solid #fff;\n"
"    border-top: none;\n"
"    border-right: none;\n"
"    content: \"\";\n"
"    height: 6px;\n"
"    left: 8px;\n"
"    opacity: 0;\n"
"    position: absolute;\n"
"    top: 9px;\n"
"    transform: rotate(-45deg);\n"
"    width: 12px;\n"
"  }\n"
"\n"
"\n"
"")
        self.pa_env.setObjectName("pa_env")
        self.gridLayout_2.addWidget(self.pa_env, 8, 2, 1, 1)
        self.db_path = QtWidgets.QComboBox(self.verticalFrame)
        self.db_path.setStyleSheet("")
        self.db_path.setObjectName("db_path")
        self.gridLayout_2.addWidget(self.db_path, 2, 2, 1, 1)
        self.anaconda = QtWidgets.QLabel(self.verticalFrame)
        self.anaconda.setMinimumSize(QtCore.QSize(0, 30))
        self.anaconda.setStyleSheet("color: rgb(120, 120, 120);")
        self.anaconda.setObjectName("anaconda")
        self.gridLayout_2.addWidget(self.anaconda, 7, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalFrame)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 1, 1, 1)
        self.outfmt = QtWidgets.QLineEdit(self.verticalFrame)
        self.outfmt.setMinimumSize(QtCore.QSize(0, 30))
        self.outfmt.setObjectName("outfmt")
        self.gridLayout_2.addWidget(self.outfmt, 6, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.verticalFrame)
        self.label_18.setMinimumSize(QtCore.QSize(0, 31))
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 2, 1, 1)
        self.start = QtWidgets.QPushButton(self.verticalFrame)
        self.start.setMinimumSize(QtCore.QSize(0, 30))
        self.start.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid rgba(0,45,48,255);\n"
"    border-radius: 5px;    \n"
"    background-color: rgba(0,45,48,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(4,76,82);\n"
"    border: 2px solid rgb(4,76,82);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 9, 2, 1, 1)
        self.reset = QtWidgets.QPushButton(self.verticalFrame)
        self.reset.setMinimumSize(QtCore.QSize(50, 30))
        self.reset.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: 2px solid rgba(0,45,48,255);\n"
"    border-radius: 5px;    \n"
"    background-color: rgba(0,45,48,255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(4,76,82);\n"
"    border: 2px solid rgb(4,76,82);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.reset.setObjectName("reset")
        self.gridLayout_2.addWidget(self.reset, 9, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalFrame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.verticalFrame)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalFrame)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_14.setStyleSheet("font: 12pt \"Arkhip\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalFrame)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 3))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 1, 1, 1)
        self.frame_div_content_2.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title_bar_top.setText(_translate("MainWindow", "HPC-Annotator"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.label_3.setText(_translate("MainWindow", "Number of processes (how many parts to divide the computation )"))
        self.label_2.setText(_translate("MainWindow", "Partition (Slurm partition to use, must be a parallel partition)"))
        self.label_11.setText(_translate("MainWindow", "User Slurm settings"))
        self.label_4.setText(_translate("MainWindow", "Memory per node (RAM to reserve to each process in GB)"))
        self.label_6.setText(_translate("MainWindow", "Number of threads (cpus-per-task) the optimal value is >32"))
        self.label.setText(_translate("MainWindow", "Account (the project account used for Slurm settings)"))
        self.label_5.setText(_translate("MainWindow", "Wall time (expected runtime of each process in hours)"))
        self.serial_partition.setText(_translate("MainWindow", "Invalid serial partition:"))
        self.input_path.setText(_translate("MainWindow", "/path/to/query.fasta"))
        self.label_20.setText(_translate("MainWindow", "Blast output format: es. (\"6 qseqid sseqid slen gaps sseq\")"))
        self.label_23.setText(_translate("MainWindow", "Select the Diamond function"))
        self.label_13.setText(_translate("MainWindow", "Binary path (the absolute binary path to use in the HPC filesystem)"))
        self.label_17.setText(_translate("MainWindow", "Select the software to use"))
        self.diamond.setText(_translate("MainWindow", "Diamond"))
        self.blast.setText(_translate("MainWindow", "Blast"))
        self.pa_env.setText(_translate("MainWindow", "Include Anaconda Env"))
        self.anaconda.setText(_translate("MainWindow", "Invalid Anaconda module:"))
        self.label_12.setText(_translate("MainWindow", "Input path (the absolute inputh path to use in the HPC filesystem)"))
        self.label_18.setText(_translate("MainWindow", "Database path (the absolute database path to use in the HPC filesystem)"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.label_10.setText(_translate("MainWindow", " "))
        self.label_15.setText(_translate("MainWindow", " "))
        self.label_14.setText(_translate("MainWindow", "Software settings"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
